server:
  port: 8080

mybatis:
  #Mapper.xml
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

mapper:
    mappers:
        - com.blog.util.BaseMapper
    not-empty: false
    identity: mysql

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: false
    params: count=countSql

spring:
  datasource:
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    # connection
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 199272xz

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data.mongodb: DEBUG
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    org.apache: INFO
    org.mongodb.driver: INFO
    com.blog: DEBUG